apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: git-sub
  name: local-git-artifacts-sub
  namespace: acm-lab
spec:
  channel: acm-channels/ch-lab-git
  type: Git
  placement:
    local: true
