apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: charts/helloworld-helm
  name: helloworld-chart-sub
  namespace: acm-lab
  labels:
    app: helloworld
spec:
  channel: acm-channels/ch-lab-git
  type: Git
  placement:
    placementRef:
      kind: PlacementRule
      name: helloworld-placement-1
  packageOverrides:
    - packageName: helloworld-helm
      packageOverrides:
        - path: spec
          value:
            replicaCount: 2

