apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: mortgage
  name: mortgage-placement-1
  namespace: acm-lab
spec:
  clusterSelector:
    matchLabels:
      environment: demo
