apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: charts/mortgage-helm
  name: mortgage-chart-sub
  namespace: acm-lab
  labels:
    app: mortgage
spec:
  channel: acm-channels/ch-lab-git
  type: Git
  placement:
    placementRef:
      kind: PlacementRule
      name: mortgage-placement-1